server:
  port: 8085
spring:
  application:
    name: loveblood-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # 注册到nacos,服务注册
    gateway:
      routes:
        - id: loveblood-gateway
#          uri: http://localhost:8087
          uri: lb://loveblood-poster
          order: 1
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/love_blood?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: xiaowei233


  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 180000